import './globals.css';

import { Header } from '@/app/components/header/index';

import { ThemeProviders } from './components/Wrapper/ThemeProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`mx-auto max-w-xl py-[128px] text-2xl`}>
        <ThemeProviders>
          <Header />
          <main>{children}</main>
        </ThemeProviders>
      </body>
    </html>
  );
}
