import './globals.css';

import { Nav } from '@/app/components/nav/index';
import { nanumBrushScript } from '@/utils/fonts';

import { ThemeProviders } from './components/Wrapper/ThemeProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${nanumBrushScript.className} mx-auto max-w-xl py-[128px] text-2xl`}
      >
        <ThemeProviders>
          <Nav />
          <main>{children}</main>
        </ThemeProviders>
      </body>
    </html>
  );
}
